
version: "3"
services:
  backend_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - app-network
    

  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend_service


networks:
  app-network:
    driver: bridge

    
    